<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260331130651 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE geo_point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, station_code VARCHAR(64) DEFAULT NULL, station_name VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, timestamp DATE NOT NULL, date DATE NOT NULL, created_at DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE pollution_measurements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pm10_value DOUBLE PRECISION DEFAULT NULL, pm10_score DOUBLE PRECISION DEFAULT NULL, pm25_value DOUBLE PRECISION DEFAULT NULL, pm25_score DOUBLE PRECISION DEFAULT NULL, no2_value DOUBLE PRECISION DEFAULT NULL, no2_score DOUBLE PRECISION DEFAULT NULL, so2_value DOUBLE PRECISION DEFAULT NULL, so2_score DOUBLE PRECISION DEFAULT NULL, o3_value DOUBLE PRECISION DEFAULT NULL, o3_score DOUBLE PRECISION DEFAULT NULL, co_value DOUBLE PRECISION DEFAULT NULL, co_score DOUBLE PRECISION DEFAULT NULL, score DOUBLE PRECISION DEFAULT NULL, date DATE NOT NULL, created_at DATE NOT NULL, geo_point_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B01D02982E91B903 ON pollution_measurements (geo_point_id)');
        $this->addSql('CREATE TABLE weather_measurements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, temperature_real DOUBLE PRECISION DEFAULT NULL, temperature_feels_like DOUBLE PRECISION DEFAULT NULL, humidity DOUBLE PRECISION DEFAULT NULL, wind_direction DOUBLE PRECISION DEFAULT NULL, wind_speed DOUBLE PRECISION DEFAULT NULL, pressure DOUBLE PRECISION DEFAULT NULL, score DOUBLE PRECISION DEFAULT NULL, date DATE NOT NULL, created_at DATE NOT NULL, geo_point_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7F2753EF2E91B903 ON weather_measurements (geo_point_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE pollution_measurements ADD CONSTRAINT FK_B01D02982E91B903 FOREIGN KEY (geo_point_id) REFERENCES geo_point (id)');
        $this->addSql('ALTER TABLE weather_measurements ADD CONSTRAINT FK_7F2753EF2E91B903 FOREIGN KEY (geo_point_id) REFERENCES geo_point (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pollution_measurements DROP CONSTRAINT FK_B01D02982E91B903');
        $this->addSql('ALTER TABLE weather_measurements DROP CONSTRAINT FK_7F2753EF2E91B903');
        $this->addSql('DROP TABLE geo_point');
        $this->addSql('DROP TABLE pollution_measurements');
        $this->addSql('DROP TABLE weather_measurements');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
